### ISSUE TITLE
Cleanup and Audit - Bug Tracker

### ISSUE THREAD

**Issue by Rixxan** [HullSeals/bug-tracker#2]
As part of 2.1, the existing code in this repository should be reviewed. 

- [ ] Are we using the site global theme?
- [ ] Is all code as efficient as possible?
- [ ] What errors, if any, are present in the current code?
- [ ] Are any unused assets removed?
- [ ] Can any pages be merged or the number of unique pages reduced?
- [ ] Are page authors and descriptions properly set?
- [ ] Is all user input validated?

NOTE: This audit has been delayed in lieu of a more substantial rewrite.

**Comment by Rixxan** [comment]
marked this issue as related to #3

**Comment by Rixxan** [comment]
Delaying to 2.1, bug system is sufficient for now (and probably should be rewritten from scratch, but that's a later problem)
